### ISSUE TITLE
regarding installation issue 

### ISSUE THREAD

**Issue by mano2991** [HudsonAlpha/VarSight#2]
I could not able to install or find the package called codicem. wether the link of the given pipeline is changed or removed from the webpage

**Comment by holtjma** [comment]
Hello, to my knowledge, Codicem is not a freely available tool (i.e. there isn't a download URL for it, likely due to the complexity of setting it up).  If you're interested in using it, you can reach out to the Software Engineering group at HudsonAlpha (https://hudsonalpha.org/softwareengineering/).
